// Frases do desafio do dia: mais de 366, para um ano inteiro sem repetição.
export const FRASES = [
  "O gato derrubou o copo, olhou para mim e saiu andando sem pedir desculpas. Dez minutos depois, voltou miando na porta da cozinha, como se nada tivesse acontecido.",
  "Às sextas, a padaria da esquina faz pão de queijo com o dobro de queijo. A fila começa antes das sete, e quem chega depois das oito só sente o cheiro.",
  "O domingo passou tão rápido que parecia ter só metade das horas. Entre o almoço demorado e o cochilo da tarde, quando vimos, já era hora de pensar na segunda.",
  "Três xícaras de farinha, dois ovos, uma de açúcar e uma pitada de paciência. O resto da receita estava escrito à mão, com uma letra que só a minha tia entendia.",
  "A última peça do quebra-cabeça estava embaixo do sofá desde o começo. Foram mil peças, duas semanas de trabalho e um cachorro muito suspeito.",
  "Choveu a tarde inteira, e o cheiro de terra molhada entrou pela janela. Na rua, as crianças pulavam nas poças enquanto os adultos corriam atrás de um lugar coberto.",
  "Meu irmão jura que viu um disco voador sobre o prédio, piscando luzes coloridas. Na manhã seguinte, descobrimos que era só o drone novo do vizinho do quinto andar.",
  "A impressora sempre sabe quando o documento é urgente. Ela espera você estar com pressa para mostrar uma mensagem de erro que ninguém no escritório consegue entender.",
  "Na praia, o sorvete derrete mais rápido do que a gente consegue tomar. Sobra uma mão grudenta, um sorriso satisfeito e a vontade de pedir mais um de outro sabor.",
  "O segredo de um bom café é a água quente, mas nunca fervendo. O pó precisa ser fresco, a xícara deve estar aquecida e a conversa, de preferência, sem pressa.",
  "Dormi cedo, acordei com disposição e mesmo assim perdi o ônibus. Descobri no ponto que o despertador ainda estava no horário de verão do ano passado.",
  "A bicicleta ficou anos na garagem, esperando alguém calibrar os pneus. Num sábado de sol, finalmente saiu para uma volta no parque e parecia até mais feliz que eu.",
  "Toda festa de família tem um tio que conta a mesma piada todo ano. A graça já não está na piada, mas em ver todo mundo rir na hora certa, como num ensaio.",
  "O pôr do sol visto do alto do morro valeu cada degrau da escadaria. Lá de cima, a cidade inteira ficava laranja, e ninguém quis ser o primeiro a descer.",
  "Ler antes de dormir é o jeito mais fácil de esquecer o celular. Uma página vira duas, duas viram um capítulo, e quando você percebe já passou da meia-noite.",
  "O controle remoto sumiu de novo, e ninguém lembra quem viu por último. Depois de revirar a sala inteira, ele apareceu dentro da geladeira, ao lado do queijo.",
  "Na horta da escola, os alunos colheram tomates, alface e muita curiosidade. Cada um levou uma muda para casa, com a promessa de regar todos os dias.",
  "O vento levou o guarda-chuva, e eu fiquei só com o cabo na mão. Cheguei ao trabalho com a roupa encharcada, mas com uma história ótima para contar.",
  "Aprender algo novo aos poucos, todos os dias, rende mais do que correr. Dez minutos de prática diária valem mais do que uma maratona no fim de semana.",
  "O filme era tão bom que ninguém reparou que a pipoca tinha acabado. Quando as luzes acenderam, o balde estava vazio e a sala inteira aplaudiu de pé.",
  "Arrumar a mala é fácil; difícil é fechar o zíper depois. Sempre sobra um par de sapatos, um casaco a mais e aquele livro que você não vai abrir na viagem.",
  "O papagaio da vizinha aprendeu a imitar o toque do meu telefone. Agora, toda manhã, eu corro para atender uma ligação que nunca existiu.",
  "Uma caminhada curta depois do almoço deixa a tarde bem mais leve. O corpo agradece, a cabeça descansa e as ideias costumam aparecer no meio do caminho.",
  "Na biblioteca, o silêncio é tanto que dá para ouvir as páginas virando. Foi lá que eu descobri que um bom livro pode fazer uma tarde inteira passar num instante.",
  "O time perdia por dois gols, mas a torcida não parou de cantar um minuto. No último lance, a bola entrou, e o estádio inteiro explodiu de alegria.",
  "Quem digita com calma e sem errar termina antes de quem corre e corrige. Cada tecla apagada é um segundo perdido, e os segundos somam mais rápido do que parece.",
  "O bolo de cenoura com cobertura de chocolate sumiu antes do café. Sobraram só algumas migalhas no prato e a promessa de fazer outro no fim de semana.",
  "As estrelas aparecem melhor longe das luzes da cidade grande. Numa noite sem nuvens no campo, dá para ver tantas que parece que alguém espalhou açúcar no céu.",
  "Hoje é um ótimo dia para começar aquilo que você vem adiando. Não precisa ser perfeito nem grandioso: o primeiro passo, por menor que seja, já conta.",
  "A feira de artesanato da praça reunia de tudo um pouco: cestos, cerâmica, doces caseiros e brinquedos de madeira. Difícil era sair de lá de mãos vazias.",
  "O elevador parou entre dois andares, e seis desconhecidos ficaram presos juntos. Em vinte minutos, já tinham trocado receitas, dicas de séries e telefones.",
  "A vizinha de cima rega as plantas sempre na mesma hora. Quem passa pela calçada às seis da tarde já aprendeu a desviar das gotas que caem da varanda.",
  "O mapa dizia que a cachoeira ficava a quinze minutos de caminhada. Uma hora e meia depois, suados e rindo, chegamos e entendemos que tinha valido a pena.",
  "Na mudança, as caixas foram etiquetadas com todo o cuidado. Mesmo assim, as panelas apareceram na caixa do banheiro e as toalhas foram parar na cozinha.",
  "O cachorro aprendeu a abrir a porta do quintal com o focinho. Agora ninguém mais precisa levantar para deixá-lo sair, mas também ninguém sabe quando ele volta.",
  "A professora de piano dizia que errar uma nota não é problema. O problema, segundo ela, é parar no meio da música com medo de errar a próxima.",
  "O pão de forma caiu com a manteiga virada para baixo, como sempre. Alguém sugeriu que era uma lei da física, e a discussão durou o café da manhã inteiro.",
  "Na roça, o galo canta antes de o sol aparecer, faça chuva ou faça frio. Na cidade, quem faz esse papel é o caminhão do lixo, só que bem menos afinado.",
  "O prato mais pedido do restaurante era um arroz simples, com feijão, ovo e farofa. O dono dizia que o segredo era o tempero da avó, guardado a sete chaves.",
  "A criança perguntou por que o céu é azul, e ninguém na mesa soube responder direito. Depois de muitas teorias, todo mundo foi pesquisar no celular ao mesmo tempo.",
  "O ônibus passou lotado, e o próximo demorou quarenta minutos. Quando finalmente chegou, estava vazio, e todo mundo pôde escolher a janela preferida.",
  "A goteira da sala só aparece quando chove com vento do sul. Por isso, a família inteira virou especialista em previsão do tempo sem querer.",
  "O sorveteiro da praça conhece o sabor preferido de cada criança do bairro. Quando alguém resolve experimentar outro, ele faz cara de surpresa e dá uma colher a mais.",
  "A planta que parecia morta ganhou uma folha nova depois de um mês na janela. Foi comemorada como se fosse um troféu, com foto e tudo.",
  "O jogo de tabuleiro prometia durar uma hora. Às duas da manhã, ainda havia gente discutindo as regras e ninguém queria admitir a derrota.",
  "Nas férias, a casa da praia vira um acampamento: colchões pela sala, toalhas no varal e areia em todos os cantos. Ninguém reclama, porque faz parte da diversão.",
  "O carteiro deixou o pacote na casa errada, e o vizinho veio entregar com um bolo. Desde então, as duas famílias se encontram todo sábado para o café.",
  "A receita pedia uma colher de fermento, mas caiu meio pacote sem querer. O bolo cresceu tanto que transbordou da forma e virou a sobremesa mais famosa da família.",
  "O metrô estava tão cheio que dava para ficar em pé sem segurar em nada. Na estação seguinte, metade desceu, e todo mundo finalmente conseguiu respirar.",
  "Na escola, a hora do recreio parecia sempre mais curta que as aulas. Bastava tirar o lanche da mochila para o sinal tocar de novo.",
  "O relógio da sala atrasa cinco minutos, e todo mundo em casa já sabe disso. O único que ainda cai na armadilha é o visitante, que sempre chega cedo demais.",
  "A trilha sonora do filme ficou na cabeça a semana inteira. No trabalho, no banho e no ônibus, a mesma melodia tocava sem parar, como um disco arranhado.",
  "O pé de manga do quintal deu tanta fruta que ninguém conseguiu dar conta. Os vizinhos ganharam sacolas, e mesmo assim ainda sobrou para fazer suco e doce.",
  "A loja anunciava uma liquidação imperdível, e a fila dobrava o quarteirão. Depois de duas horas esperando, a última peça do tamanho certo tinha acabado de ser vendida.",
  "Na beira do rio, os pescadores ficam horas em silêncio, só esperando. Às vezes o peixe nem morde a isca, mas ninguém parece se importar com isso.",
  "O aniversário surpresa quase foi descoberto por causa de uma mensagem enviada no grupo errado. Por sorte, a pessoa homenageada nunca lê as mensagens do grupo da família.",
  "A chaleira começou a apitar no exato momento em que a ligação importante começou. Foram cinco minutos de conversa com um assobio agudo ao fundo.",
  "O jardineiro da praça conversa com as roseiras enquanto trabalha. Ele jura que elas florescem mais bonitas quando ouvem elogios todos os dias.",
  "Quando falta luz no bairro, os vizinhos saem para a calçada. Sem televisão nem internet, as conversas se estendem e alguém sempre aparece com um violão.",
  "A sopa da avó curava qualquer coisa, de resfriado a coração partido. A receita nunca foi escrita, e cada neto jura que se lembra dela de um jeito diferente.",
  "A cidade amanheceu coberta de neblina, e o prédio da frente desapareceu. Por algumas horas, parecia que a rua terminava no meio do nada.",
  "O pipoqueiro da porta da escola sabe a hora exata em que o sinal vai tocar. Dois minutos antes, a panela já está estourando e o cheiro chega até as salas.",
  "A gaveta da cozinha guarda de tudo: pilhas, elásticos, chaves sem dono e manuais de aparelhos que nem existem mais. Ninguém tem coragem de jogar nada fora.",
  "O passarinho fez ninho dentro do vaso da varanda. Durante semanas, a família inteira regou as outras plantas na ponta dos pés para não incomodar os filhotes.",
  "Na estrada, a placa anunciava o melhor pastel da região a cinco quilômetros. Depois de passar por outras dez placas iguais, a fome venceu e paramos na primeira.",
  "O vizinho do lado ensaia bateria todo sábado às dez da manhã. Depois de um ano, o prédio inteiro já sabe cantar as músicas do repertório dele.",
  "A máquina de lavar terminou o ciclo com uma meia a menos, como sempre. Há quem diga que existe um mundo paralelo cheio de meias perdidas esperando seus pares.",
  "O cachorro sabe exatamente quando alguém está abrindo um pacote de biscoito. Pode estar no fundo do quintal, dormindo, que em três segundos aparece na cozinha.",
  "Na feira, o vendedor de abacaxi oferece uma fatia para cada pessoa que passa. Quase ninguém resiste, e a barraca dele é sempre a mais movimentada da rua.",
  "A criança montou uma cabana com lençóis e cadeiras no meio da sala. Passou a tarde inteira lá dentro, lendo com uma lanterna, mesmo com o sol entrando pela janela.",
  "O trem atrasou por causa de uma vaca que resolveu descansar nos trilhos. O maquinista buzinou, esperou com paciência e só seguiu quando ela foi embora sozinha.",
  "A torta de limão da confeitaria acaba sempre antes do meio-dia. Quem quer garantir uma fatia precisa encomendar no dia anterior e chegar com a senha na mão.",
  "O celular caiu dentro do balde de água, e a solução foi um pote de arroz. Dois dias depois, ele voltou a funcionar como se nada tivesse acontecido.",
  "No inverno, o cobertor mais disputado da casa é o mais velho e mais macio. Quem levanta do sofá para pegar água sabe que vai voltar e encontrar o lugar ocupado.",
  "O artista de rua pintava retratos em cinco minutos, só com carvão e papel. A fila de curiosos crescia, e cada desenho saía mais parecido que o anterior.",
  "A caixa de fotos antigas apareceu no fundo do armário durante a faxina. A limpeza parou na hora, e o resto da tarde foi de risadas e histórias esquecidas.",
  "O farol da esquina fica vermelho por tanto tempo que os motoristas já desligam o carro. Quando abre, metade da fila ainda está procurando a chave.",
  "O sabiá canta todo dia no mesmo galho da árvore em frente à janela. Já virou o despertador da casa, mais pontual que qualquer aparelho.",
  "No acampamento, a barraca foi montada ao contrário e só perceberam à noite. Dormiram assim mesmo, rindo, e o sol entrou pela porta errada de manhã.",
  "O pastel de feira tem que ser comido na hora, ainda quente, com caldo de cana. Levar para casa não adianta: no caminho, ele perde metade da graça.",
  "A tartaruga do zoológico tem mais de cem anos e já viu muita coisa mudar. Mesmo assim, continua sem pressa nenhuma, como se o tempo fosse dela.",
  "A pia da cozinha entupiu bem no dia do almoço de família. Enquanto um primo tentava consertar, o resto da turma lavava a louça no tanque do quintal.",
  "O livro estava esquecido na estante havia anos, coberto de poeira. Bastou abrir na primeira página para a noite inteira desaparecer sem ninguém perceber.",
  "O motorista de táxi contou a história de sua vida em vinte minutos de corrida. No fim, a passageira quase pediu para dar mais uma volta no quarteirão.",
  "Na quermesse da paróquia, a pescaria era a barraca mais disputada pelas crianças. Os prêmios eram simples, mas a emoção de puxar a vara não tinha preço.",
  "O ventilador de teto faz um barulho estranho a cada volta. Ninguém sabe consertar, e todo mundo já se acostumou a dormir com aquele ritmo constante.",
  "A moça da padaria sabe o pedido de cada cliente de cor. Basta entrar pela porta para os dois pães e o queijo fatiado já estarem embrulhados no balcão.",
  "A primeira neve que a criança viu na vida foi numa viagem para o sul. Ela ficou tão encantada que tentou levar um pouco para casa dentro de uma garrafa.",
  "O jardim de inverno da casa virou o canto preferido do gato. Ele passa as tardes ali, seguindo o sol de um lado para o outro, sem pressa nenhuma.",
  "O bairro fez um mutirão para pintar a praça abandonada. Em um fim de semana, os bancos ganharam cor, os canteiros ganharam flores e as crianças voltaram a brincar.",
  "A senha do wi-fi da casa da avó é o nome do primeiro cachorro da família. Todo mundo que visita precisa ouvir a história inteira antes de conseguir conectar.",
  "O barco saiu cedo, quando a neblina ainda cobria o rio. Aos poucos, as margens foram aparecendo, e com elas os primeiros pássaros do dia.",
  "Na loja de discos usados, o vendedor recomenda álbuns como quem receita remédio. Diz que cada música certa na hora certa pode mudar o dia de qualquer um.",
  "O bolo de aniversário tinha tantas velas que disparou o alarme de incêndio. Os bombeiros chegaram, riram muito e ainda ganharam uma fatia cada um.",
  "A casa nova tinha um quintal enorme, mas nenhuma sombra. A primeira coisa que a família fez foi plantar uma árvore e combinar de fazer um piquenique embaixo dela.",
  "O despertador tocou, foi adiado três vezes e acabou esquecido. Felizmente, era sábado, e ninguém tinha compromisso algum antes do almoço.",
  "Na estação de trem, um senhor toca acordeão todas as manhãs. Os passageiros apressados diminuem o passo sem perceber, só para ouvir mais um pouco.",
  "A goiabada com queijo é a sobremesa mais simples e mais disputada da casa. Basta abrir a geladeira para alguém aparecer perguntando se ainda sobrou.",
  "O mecânico ouviu o barulho do carro por dez segundos e já sabia o problema. Disse que motor é como gente: cada um reclama de um jeito diferente.",
  "O caderno de receitas da família tem manchas de óleo, chocolate e café. Cada mancha conta uma história, e ninguém tem coragem de passar a limpo.",
  "No parque, um grupo de idosos pratica alongamento todas as manhãs. Os mais novos que passam correndo sempre param para ver e, às vezes, até participam.",
  "O cachorro da padaria dorme na porta, e os clientes passam por cima dele com cuidado. Ele só levanta quando o padeiro tira a fornada da manhã.",
  "A conta do restaurante chegou, e começou a matemática da divisão. Depois de muito cálculo, alguém percebeu que a sobremesa tinha sido esquecida.",
  "Na beira da estrada, uma placa feita à mão dizia: \"Mel puro, pode confiar.\" O pote custava pouco, e o sabor era muito melhor do que o de qualquer mercado.",
  "O inverno chegou de repente, e todo mundo correu atrás dos casacos guardados. Num dos bolsos, apareceu uma nota esquecida desde o ano passado.",
  "A orquestra da escola tinha mais entusiasmo do que afinação. Mesmo assim, no fim da apresentação, os pais aplaudiram de pé e pediram bis.",
  "O mercadinho do bairro vende fiado para quem mora ali há muito tempo. A caderneta fica embaixo do balcão, cheia de nomes, números e muita confiança.",
  "Na festa junina, a quadrilha ensaiou durante um mês inteiro. No dia, metade dos passos foi esquecida, mas ninguém deixou de dançar e sorrir.",
  "O guarda-roupa range toda vez que alguém abre a porta de madeira. Já virou um alarme involuntário: impossível pegar um casaco sem acordar a casa toda.",
  "A cozinheira do refeitório lembrava o nome de todos os alunos da escola. Quem estava triste ganhava uma porção extra de batata frita, sem precisar pedir.",
  "O voo atrasou três horas, e o saguão do aeroporto virou uma sala de estar. Desconhecidos dividiam tomadas, histórias e até pacotes de biscoito.",
  "A tempestade derrubou a energia, e o jantar foi à luz de velas. Ninguém tinha planejado, mas aquela foi a noite mais tranquila da semana.",
  "O feirante gritava que sua banana era a mais doce do Brasil. Ninguém sabia se era verdade, mas a banca dele vivia cheia de gente querendo conferir.",
  "A bicicleta ergométrica comprada em janeiro virou cabide em março. Hoje, ela segura duas camisas, um casaco e muitas boas intenções.",
  "O pôster do filme preferido ficou desbotado de tanto sol na parede do quarto. Mesmo assim, ninguém tem coragem de tirar, porque ele já faz parte da casa.",
  "Na roda de samba, ninguém precisa ser convidado para cantar junto. Basta conhecer o refrão, bater palmas no ritmo e deixar a alegria fazer o resto.",
  "O pão caseiro levou a tarde inteira para ficar pronto. Saiu do forno com a casca dourada e foi devorado em dez minutos, ainda quente, com manteiga.",
  "O vizinho idoso conhece a história de cada casa da rua. Ele conta quem morou ali antes, quem plantou cada árvore e onde ficava o antigo campinho.",
  "A criança encontrou um caramujo no jardim e deu a ele um nome importante. Durante a semana, visitou o novo amigo todos os dias, sempre com uma folha de alface.",
  "O casamento ao ar livre foi interrompido por uma chuva rápida. Os convidados correram para debaixo da tenda, e a festa ficou ainda mais animada.",
  "No cinema antigo da cidade, as poltronas rangem e a tela tem um risco no canto. Mesmo assim, as sessões de domingo continuam lotadas, como antigamente.",
  "O aquário do consultório acalmava todo mundo na sala de espera. As crianças contavam os peixes, e os adultos esqueciam por um instante o motivo da consulta.",
  "A barraca de churros ficava na saída do parque, estrategicamente posicionada. Depois de uma tarde inteira de brincadeiras, ninguém conseguia passar sem parar.",
  "O telefone fixo da casa só toca para oferecer promoções. Mesmo assim, quando ele toca, todo mundo corre para atender, com aquela esperança de novidade.",
  "O jabuti da família foge para o quintal do vizinho uma vez por ano. Ninguém sabe como ele consegue, já que leva meia hora para atravessar a sala.",
  "A sorveteria lançou um sabor novo de milho verde com coco. Os mais desconfiados torceram o nariz, mas em uma semana ele já era o mais vendido.",
  "A cidadezinha tem uma única rua principal, uma igreja e uma praça com coreto. Aos domingos, parece que todos os moradores se encontram ali ao mesmo tempo.",
  "O despertador do celular tocou no meio da reunião, com a música mais animada possível. A sala inteira riu, e a reunião ficou bem mais leve depois disso.",
  "O caminhão de mudança chegou, e os vizinhos curiosos foram para as janelas. Em poucos minutos, a rua inteira já sabia que os novos moradores tinham um piano.",
  "A piscina do clube estava gelada, mas as crianças pularam assim mesmo. Os adultos ficaram na borda, só com os pés na água, dizendo que estava ótima.",
  "O brigadeiro da festa sumiu antes de cantarem os parabéns. Os suspeitos foram encontrados embaixo da mesa, com a boca suja de chocolate.",
  "A loja de ferragens do bairro tem de tudo, de parafusos a panelas. O dono sabe onde está cada item, mesmo que ninguém mais consiga entender a organização.",
  "A viagem de carro tinha uma regra: quem estivesse no banco da frente escolhia a música. Por isso, a disputa por aquele lugar começava ainda na garagem.",
  "O lagarto tomava sol na pedra do jardim todos os dias às dez horas. Quando nublava, ele parecia desapontado, olhando para o céu como quem espera explicações.",
  "Na barbearia antiga, as conversas sobre futebol duravam mais do que os cortes. Alguns clientes iam até lá só para conversar, mesmo sem precisar de corte.",
  "O pé de jabuticaba encheu de frutas de uma vez só, até o tronco ficou preto. As crianças subiram nos galhos e comeram tanto que nem quiseram jantar.",
  "A feira de ciências da escola teve vulcões, robôs e até uma horta suspensa. O projeto vencedor foi um sistema simples para economizar água na escola.",
  "O gato se deitou bem em cima do teclado do computador. Escreveu sozinho uma linha inteira de letras sem sentido e depois dormiu satisfeito.",
  "A banda da cidade tocou no coreto, como fazia todos os domingos de manhã. Os músicos já eram idosos, mas o entusiasmo era o mesmo de cinquenta anos atrás.",
  "O guarda-chuva esquecido no ônibus fez falta logo na descida. Bastou pisar na calçada para a chuva, que estava fraca, virar um temporal daqueles.",
  "A maratona de séries começou na sexta à noite e só terminou no domingo. Ao fim, ninguém se lembrava direito do que tinha comido no fim de semana.",
  "O vendedor de picolé passa na praia gritando os sabores em ordem alfabética. Os banhistas já esperam o momento do sabor favorito para levantar a mão.",
  "A colcha de retalhos foi costurada pela bisavó, com pedaços de roupas da família. Cada quadrado guarda uma lembrança diferente de alguém querido.",
  "O parque aquático estava cheio, e a fila do tobogã parecia não ter fim. Depois de uma hora esperando, a descida durou sete segundos e valeu cada um deles.",
  "O carro velho do avô só pega no tranco, empurrado pela família inteira. Mesmo assim, ninguém quer vender, porque ele já faz parte de todas as histórias.",
  "A primeira tentativa de fazer pão em casa terminou com algo parecido com um tijolo. A segunda melhorou, e na quinta o cheiro já fazia os vizinhos perguntarem.",
  "Na pescaria, quem pegou o maior peixe foi justamente a pessoa que nunca tinha pescado. Os mais experientes passaram o resto do dia tentando entender o segredo.",
  "O bebê aprendeu a bater palmas e agora aplaude tudo que acontece em casa. A chaleira apitando, a porta abrindo e até o cachorro latindo recebem ovação.",
  "A manhã de feriado começou com cheiro de café e pão na chapa. Sem pressa, sem despertador e sem compromisso, a cozinha virou o melhor lugar do mundo.",
  "A loja de brinquedos antigos tinha piões, bolinhas de gude e carrinhos de lata. Os adultos entravam para comprar presentes e saíam com algo para si mesmos.",
  "O motorista do ônibus escolar cumprimentava cada criança pelo nome. No último dia de aula, recebeu tantos desenhos que encheu o painel do veículo.",
  "A chuva de verão chegou de repente e foi embora em quinze minutos. Deixou o ar fresco, as ruas brilhando e um arco-íris enorme sobre os prédios.",
  "O mercado municipal tem cheiro de tempero, fruta madura e café torrado. Andar pelos corredores é como fazer uma viagem rápida por vários lugares do país.",
  "A pizza chegou com o sabor errado, mas ninguém teve coragem de reclamar. No fim, todos concordaram que tinha sido a melhor escolha da noite.",
  "O cachorro adotado tinha medo de tudo nos primeiros dias. Um mês depois, já dormia no sofá, roubava meias e latia para o carteiro como dono da casa.",
  "O professor de história contava as aulas como se fossem aventuras. Os alunos esqueciam de olhar o relógio e reclamavam quando o sinal tocava.",
  "A rede da varanda é o lugar mais disputado da casa depois do almoço. Quem chega primeiro ganha o cochilo, e quem chega depois fica balançando os outros.",
  "Na viagem de ônibus, o passageiro do lado contou que ia conhecer o mar pela primeira vez. Quando a praia apareceu na janela, o ônibus inteiro comemorou junto.",
  "A floricultura da esquina monta buquês que parecem pinturas. A florista diz que cada flor tem uma personalidade e que é preciso saber combinar.",
  "O muro da escola ganhou um mural pintado pelos próprios alunos. Cada turma ficou responsável por um pedaço, e o resultado virou ponto de encontro do bairro.",
  "O lanche da excursão foi preparado na véspera com todo o cuidado. Na hora de comer, descobriram que os sanduíches tinham ficado no banco do ônibus.",
  "O ipê da avenida floresceu de amarelo e mudou a paisagem da cidade. Durante uma semana, os carros andavam mais devagar só para os motoristas olharem.",
  "A vitamina de banana da lanchonete vinha num copo tão grande que precisava de duas mãos. Era o café da manhã de metade dos trabalhadores da região.",
  "O quintal da casa tinha uma goiabeira perfeita para subir. As crianças passavam horas nos galhos, inventando que estavam num navio em alto-mar.",
  "O porteiro do prédio conhece todos os moradores e seus horários. Quando alguém se atrasa, ele já segura o elevador e avisa que o ônibus acabou de passar.",
  "A fogueira do acampamento reuniu todo mundo depois do jantar. As histórias de assombração foram ficando cada vez mais exageradas até ninguém querer dormir.",
  "O pedreiro trabalhava cantando, e as paredes subiam no ritmo das músicas. Quando a obra terminou, os moradores sentiram falta da trilha sonora diária.",
  "A biblioteca do bairro emprestava livros sem cobrar nada, só com a promessa de devolver. Muitos voltavam com bilhetes dentro, deixados para o próximo leitor.",
  "O piquenique no parque foi invadido por um grupo de formigas bem organizadas. Em dez minutos, elas já tinham levado metade do açúcar sem ninguém notar.",
  "A costureira do bairro ajusta roupas, troca zíperes e conserta qualquer coisa. Os clientes deixam as peças de manhã e buscam à tarde, como se fosse mágica.",
  "O cometa passou visível no céu, e a família foi para o quintal observar. Ninguém sabia direito para onde olhar, mas todos fingiram que tinham visto.",
  "O feriado prolongado esvaziou a cidade, e as ruas ficaram silenciosas. Quem ficou aproveitou para andar de bicicleta pelas avenidas sem medo do trânsito.",
  "A cozinha da escola cheirava a bolo de fubá todas as quintas-feiras. Os alunos sabiam o dia da semana só pelo aroma que chegava até a sala.",
  "A banda do casamento atrasou, e um primo assumiu o microfone com o violão. Quando os músicos chegaram, ninguém queria que ele parasse de tocar.",
  "O gato do vizinho escolheu a nossa varanda para dormir todas as tardes. Ganhou um cobertor, um pote de água e, aos poucos, um lugar na família.",
  "Na rodoviária, a lanchonete servia a melhor coxinha da cidade. Tinha gente que comprava passagem só para ter uma desculpa de passar por ali.",
  "O jardim de cactos da avó parecia sem graça até a primavera chegar. De repente, todos floresceram ao mesmo tempo, com cores que ninguém esperava.",
  "A competição de pipas reuniu crianças e adultos no campo do bairro. O vento ajudou, e o céu ficou cheio de cores, linhas e gritos de comemoração.",
  "O hotel da serra servia chocolate quente às quatro da tarde, pontualmente. Os hóspedes se reuniam perto da lareira e ninguém queria sair para passear.",
  "A capivara apareceu na beira do lago, tranquila, como quem é dona do lugar. Os visitantes do parque ficaram em silêncio, só para não espantá-la.",
  "O cozinheiro do restaurante provava cada panela antes de servir. Dizia que tempero bom não se mede com colher, mas com paciência e atenção.",
  "A estrada de terra até o sítio tinha mais buracos do que trechos lisos. Quem chegava lá, porém, era recebido com café de coador e bolo de mandioca.",
  "O desfile de carnaval da escola infantil teve fantasias de papel e muita alegria. A bateria era feita com panelas, mas o ritmo estava impecável.",
  "A vizinha deixou um pote de doce de abóbora na porta, sem bilhete nenhum. A família passou a semana tentando adivinhar de quem tinha sido o presente.",
  "O balanço do parque range de um jeito que todas as crianças do bairro reconhecem. Quando ele para de ranger, é sinal de que alguém foi chamado para jantar.",
  "A tia que mora longe manda áudios de dez minutos contando as novidades. Ninguém consegue ouvir de uma vez, mas todo mundo escuta até o fim, aos pouquinhos.",
  "O caminho até a escola passava por uma padaria, uma banca de jornal e um cachorro simpático. As crianças cumprimentavam os três todas as manhãs, sem exceção.",
  "O sol de inverno entra pela janela da sala só no meio da manhã. O gato sabe disso e se muda para aquele quadradinho de luz na hora exata.",
  "A geladeira da casa de praia tinha mais gelo do que comida. Na primeira manhã, foi preciso uma expedição inteira até o mercado para garantir o café.",
  "O coral do bairro ensaiava toda quarta-feira no salão da associação. Os vizinhos que passavam pela calçada paravam para ouvir, mesmo com pressa.",
  "A roupa estendida no varal secou em meia hora, graças ao vento forte. O problema foi recolher as peças que voaram para o quintal do vizinho.",
  "O restaurante por quilo da esquina tem uma balança que todo mundo jura estar errada. Mesmo assim, a fila no horário do almoço não diminui nunca.",
  "O artesão transformava garrafas de vidro em luminárias coloridas. Na feira, as peças dele brilhavam tanto que dava para vê-las do outro lado da praça.",
  "A criança perdeu o primeiro dente e colocou embaixo do travesseiro. De manhã, encontrou uma moeda e um bilhete com uma letra muito parecida com a da mãe.",
  "O café da roça é feito no coador de pano, com água fervida no fogão a lenha. Quem prova uma vez fica com saudade daquele sabor por muito tempo.",
  "A ponte de madeira balançava a cada passo, e o rio corria logo abaixo. Atravessar era uma pequena aventura, sempre com alguém dizendo para não olhar para baixo.",
  "O dia de faxina terminou com a casa brilhando e todo mundo exausto no sofá. Ninguém teve coragem de cozinhar, e o jantar foi pedido pelo telefone.",
  "O pintor de paredes deixou o trabalho e uma marca de mão no teto da sala. A família decidiu não apagar, e a marca virou parte da decoração.",
  "No sítio, as galinhas andavam soltas e cada uma tinha um nome. A mais brava era chamada de Rainha, e até o cachorro respeitava o espaço dela.",
  "O parquinho do condomínio estava vazio até a primeira criança aparecer. Em cinco minutos, já havia dez delas brincando de pega-pega como velhas amigas.",
  "O telhado da casa tinha uma telha solta que assobiava quando ventava forte. As crianças diziam que era o fantasma da casa cantando para dormir.",
  "O doce de leite da fazenda vinha num pote de vidro com tampa de pano. Durava, no máximo, dois dias na despensa, mesmo escondido atrás das latas.",
  "A sala de espera do dentista tinha revistas de muitos anos atrás. Folhear aquelas páginas era quase como fazer uma viagem no tempo.",
  "A moto do entregador quebrou a duas quadras do destino final. Ele terminou a entrega a pé, correndo, e a pizza chegou ainda quente.",
  "A família inteira tentou montar o móvel novo seguindo o manual. Depois de duas horas, sobraram quatro parafusos, mas o armário ficou de pé.",
  "O sol nasceu atrás das montanhas, pintando as nuvens de rosa e laranja. Quem acordou cedo para ver disse que valeu muito mais do que qualquer hora de sono.",
  "O vendedor de cocadas passava pela rua tocando um sininho. As crianças corriam para o portão antes mesmo de ele dobrar a esquina.",
  "O bolo de milho da quitanda era tão famoso que tinha lista de espera. Quem conseguia uma fatia ainda quente se sentia premiado pelo resto do dia.",
  "O jardim botânico estava cheio de plantas com nomes complicados. As crianças preferiam inventar nomes novos, bem mais divertidos que os das placas.",
  "A tomada da sala só funciona se o plugue ficar meio torto. Todo mundo em casa já sabe o jeito certo, mas as visitas sempre acham que está quebrada.",
  "O caminhão de sorvete passou tocando aquela música conhecida, e a rua inteira saiu de casa. Até os adultos correram, fingindo que era só para acompanhar as crianças.",
  "A trilha até o mirante tinha placas a cada duzentos metros. A última dizia apenas: \"Falta pouco\", e foi a mais mentirosa de todas.",
  "O pato do lago do parque segue quem estiver com um saquinho de pão na mão. Basta abrir o pacote para aparecer uma fila inteira de patos atrás.",
  "O primeiro dia de aula teve choro, abraço apertado e lancheira nova. No fim da tarde, quem chorou de manhã não queria mais ir embora da escola.",
  "A banca de jornal da esquina vende de tudo, menos jornal. Tem bala, figurinha, carregador de celular e até guarda-chuva nos dias de chuva.",
  "O microondas apitou três vezes, mas a pipoca ficou esquecida lá dentro. Quando alguém lembrou, metade dos grãos tinha estourado e a outra metade, queimado.",
  "A família adotou um cachorro grande achando que ele era filhote. Seis meses depois, ele ocupava o sofá inteiro e ainda achava que cabia no colo.",
  "O primo que mora fora chegou para as festas carregado de presentes. Quando abriu a mala, descobriu que tinha trazido a mala do vizinho de poltrona.",
  "O fogão da avó tinha uma boca que só funcionava com fósforo e paciência. Mesmo assim, era nela que saíam as melhores panelas de feijão da família.",
  "A aula de dança começou com todo mundo envergonhado, encostado na parede. No fim da noite, ninguém queria parar, nem quando a música acabou.",
  "O ar-condicionado do escritório parece ter só duas opções: frio de geladeira ou calor de deserto. Por isso, metade das pessoas trabalha de casaco.",
  "A orquestra de grilos começou assim que o sol se pôs no sítio. Quem estava acostumado com o barulho da cidade estranhou, mas dormiu como nunca.",
  "O caixa do supermercado era tão rápido que os clientes nem conseguiam ensacar as compras. A fila dele era sempre a mais procurada, mesmo sendo a maior.",
  "O pomar do sítio tinha laranjas, mexericas e limões espalhados pelo chão. As crianças voltavam com os bolsos cheios e as mãos com cheiro de casca.",
  "O espelho do banheiro embaça tanto no banho que vira um quadro para desenhar. Toda manhã, alguém deixa um recado ou um desenho diferente para o próximo.",
  "A viagem de trem pela serra levava três horas e passava por túneis e cachoeiras. Ninguém mexeu no celular, porque a janela já era espetáculo suficiente.",
  "A estante da sala tinha livros organizados por cor, não por assunto. Ficava linda, mas encontrar um título específico virou um jogo de adivinhação.",
  "O caqui do pé estava maduro, e os passarinhos chegaram antes da família. Sobraram poucos frutos, mas ninguém ficou bravo: o quintal era deles também.",
  "O professor de matemática trouxe uma pizza para explicar frações. A aula foi um sucesso, principalmente na hora de dividir as fatias de verdade.",
  "A lancheira tinha um bilhete dobrado junto com o sanduíche. A criança leu no recreio, sorriu e guardou o papel no bolso da mochila por meses.",
  "O inverno trouxe a temporada de sopas, e cada dia tinha uma diferente. A de feijão com macarrão venceu a votação da família por unanimidade.",
  "O vizinho comprou um cortador de grama novo e passou a cortar a calçada inteira. Em pouco tempo, a rua toda estava mais bonita e cheia de elogios.",
  "O tapete da sala tinha uma mancha de suco que ninguém assumia. Para resolver, a família colocou uma poltrona em cima, e o mistério ficou esquecido.",
  "A estrela cadente passou tão rápido que só uma pessoa da roda viu. Ela fez um pedido em silêncio e nunca contou para ninguém o que era.",
  "A fila do banco andava devagar, e as pessoas começaram a conversar. Quando chegou a vez de cada um, todos já sabiam a vida uns dos outros.",
  "O sanduíche de mortadela do mercadão é tão grande que vem dividido em dois. Quem tenta comer sozinho geralmente desiste e leva o resto embrulhado para casa.",
  "O cachorro da casa decidiu que o tapete do banheiro é a cama dele. Ninguém sabe o motivo, mas todo banho começa pedindo licença para o dono do lugar.",
  "A brincadeira de esconde-esconde durou tanto que um dos primos dormiu no esconderijo. Só o encontraram na hora do jantar, embaixo de uma pilha de casacos.",
  "O sol de verão deixou a areia da praia tão quente que todo mundo andava pulando. Parecia uma dança coletiva entre a toalha e o mar.",
  "O vaso de barro do quintal virou casa de um sapo bem gordo. Toda noite, ele cantava no mesmo horário, como se fosse dono do jardim inteiro.",
  "A torta salgada da festa da escola acabou em minutos e virou assunto da semana. No ano seguinte, a receita foi pedida por quase todos os pais da turma.",
  "O guarda da ronda noturna passava apitando pela rua às onze horas. Os moradores mais antigos diziam que só dormiam depois de ouvir aquele som.",
  "O cachorro do sítio acompanhava as visitas até o portão, como um anfitrião. Depois, voltava para a sombra da mangueira e esperava a próxima chegada.",
  "A loja de tecidos tinha rolos de todas as cores, empilhados até o teto. A dona sabia de cor o preço de cada metro, sem nem olhar a etiqueta.",
  "O relógio da praça bate as horas com um sino grave e demorado. Os moradores já não precisam olhar o celular: basta contar as badaladas.",
  "A tapioca da barraquinha da rodoviária era recheada com queijo e coco. Os viajantes chegavam cansados e saíam de lá com outro humor.",
  "O professor de educação física inventava jogos novos toda semana. Às vezes as regras mudavam no meio da partida, e isso deixava tudo ainda mais divertido.",
  "O sorvete de flocos caiu da casquinha logo na primeira lambida. O sorveteiro, com pena, montou outro de graça e ainda colocou uma bola extra.",
  "A biblioteca da casa da avó tinha livros com páginas amareladas e anotações nas margens. Ler aquelas observações era como conversar com quem já tinha partido.",
  "Na casa de campo, o café da manhã era servido na varanda, com vista para as montanhas. O pão vinha da cidade, mas a manteiga e o queijo eram da fazenda.",
  "O cachorro aprendeu a fingir que mancava para ganhar petisco. Funcionou por uma semana, até alguém perceber que ele mancava de patas diferentes.",
  "O caderno de desenho da criança estava cheio de dinossauros coloridos. Cada um tinha nome, idade e até um prato preferido, todos anotados com cuidado.",
  "A cidade do interior tinha um único semáforo, instalado havia pouco tempo. Os motoristas ainda paravam para admirar, mesmo quando estava verde.",
  "O mercado de pulgas do domingo vendia de tudo, de discos antigos a lustres de cristal. Quem ia só para olhar sempre voltava com alguma coisa na sacola.",
  "O passeio de barco ia até a ilha, com parada para mergulho. Os peixes coloridos chegavam tão perto que pareciam curiosos com os visitantes.",
  "A receita de lasanha tinha tantas etapas que a cozinha virou um campo de batalha. Mas, quando chegou à mesa, ninguém lembrou da bagunça na pia.",
  "O cachorro e o gato da casa dormem juntos, enrolados no mesmo cobertor. Durante o dia, fingem que não se suportam, mas à noite são inseparáveis.",
  "O vento da tarde trouxe o cheiro de churrasco de algum quintal vizinho. Ninguém sabia de onde vinha, mas a fome chegou para todo mundo da rua.",
  "A loja de sapatos tinha uma escada para alcançar as caixas do alto. O vendedor subia e descia tantas vezes por dia que nem precisava de academia.",
  "O sinal de internet da casa de praia só funcionava num canto da varanda. Por isso, quem precisava mandar mensagem ficava em pé, com o braço levantado.",
  "A primeira tentativa de andar de patins terminou com muitos tombos e risadas. Na terceira tarde, a criança já deslizava pela calçada sem segurar em ninguém.",
  "O lago congelou parcialmente numa manhã de frio intenso na serra. Os turistas tiraram fotos, e os patos ficaram parados na beira, sem entender nada.",
  "O vizinho do térreo cultiva temperos em vasos pendurados na janela. Quem passa pela calçada sente o cheiro de manjericão e hortelã sem querer.",
  "A torcida do time do bairro tinha só vinte pessoas, mas cantava como se fossem mil. Os jogadores diziam que aquele barulho valia um gol por partida.",
  "O dia de chuva cancelou o passeio, mas trouxe uma tarde de jogos de cartas. No fim, ninguém lembrava mais do passeio que tinha sido cancelado.",
  "A escada do prédio antigo tinha degraus de mármore gastos no meio. Cada desgaste contava a história de décadas de moradores subindo e descendo.",
  "O pastor alemão da casa era enorme, mas tinha medo do gato pequeno. Bastava o gato aparecer na porta para ele sair de fininho da sala.",
  "A rua inteira enfeitou as casas com luzes no fim do ano. À noite, os carros passavam devagar, e as crianças apontavam para as decorações mais bonitas.",
  "O espetáculo de mágica na escola deixou todos de boca aberta. O mágico tirou uma moeda da orelha do diretor, que fingiu indignação e depois aplaudiu.",
  "A mochila de viagem estava tão cheia que precisou de duas pessoas para fechar. No destino, metade das roupas voltou sem ter sido usada.",
  "O carrinho de pipoca doce parava na frente do cinema todas as sextas. O cheiro de açúcar queimado se espalhava pela rua e anunciava o fim de semana.",
  "O caqui caiu do pé e acertou bem o chapéu de quem passava embaixo. A pessoa olhou para cima, riu e levou a fruta para casa como presente.",
  "A vó ensinou a neta a fazer crochê numa tarde de chuva. A primeira peça saiu torta, mas foi guardada como o objeto mais valioso da casa.",
  "O trem de brinquedo dava voltas pela árvore de Natal, apitando a cada curva. O cachorro passava a noite inteira de olho, como se fosse um intruso.",
  "A sopa de letrinhas virou aula de português na mesa do jantar. As crianças tentavam formar palavras antes que as letras afundassem no prato.",
  "O passarinho entrou pela janela da sala e não sabia mais como sair. Depois de muita tentativa, saiu pela mesma janela, como se nada tivesse acontecido.",
  "O feirante do pastel sabia o nome de todos os clientes e o recheio preferido de cada um. Era só chegar perto da barraca para o pedido já estar na chapa.",
  "O muro da casa estava coberto de trepadeira florida de cima a baixo. Na primavera, as abelhas faziam tanto barulho que dava para ouvir da calçada.",
  "O cachorro pegou a bolinha e saiu correndo na direção oposta. O jogo era sempre assim: ninguém arremessava, só corria atrás dele pelo quintal.",
  "A estrada até a praia tinha uma parada obrigatória para comer pamonha. Ninguém lembra de quando a tradição começou, mas ninguém quer acabar com ela.",
  "O despertador de corda da avó toca tão alto que acorda a casa inteira. Mesmo com o celular ao lado, ela diz que confia mais nele.",
  "O sapateiro da galeria remendava sapatos que ninguém mais consertaria. Os clientes saíam de lá com o calçado novo de novo e uma boa conversa no bolso.",
  "A neblina da serra desceu de repente e escondeu a estrada inteira. Os carros seguiram devagar, um atrás do outro, guiados apenas pelas luzes da frente.",
  "O caracol subiu pela parede da varanda durante a noite inteira. De manhã, deixou um rastro brilhante, como se tivesse escrito uma mensagem secreta.",
  "O bolo de aniversário foi decorado pelas crianças com tudo que encontraram. Tinha confeito, bala de goma e até uma bolacha recheada no topo.",
  "A loja de instrumentos tinha um piano para quem quisesse experimentar. Todo fim de tarde, um desconhecido diferente sentava ali e tocava alguma coisa bonita.",
  "O vizinho de cima sempre arrasta móveis às onze da noite. Ninguém sabe o que tanto ele muda de lugar, mas o prédio inteiro já se acostumou.",
  "O jardim da escola ganhou uma horta cuidada pelos alunos do primeiro ano. Quando a primeira alface ficou pronta, foi comemorada com salada para todos.",
  "O caminhoneiro contou que conhecia cada posto da estrada pelo nome do café. Dizia que o melhor ficava num lugar sem placa, que só os antigos conheciam.",
  "O balão de festa escapou da mão da criança e subiu até sumir nas nuvens. Ela acenou para ele até o fim, desejando uma boa viagem.",
  "A peça de teatro da escola teve um cenário de papelão que balançava a cada fala. A plateia riu, os atores riram, e no fim todos aplaudiram de pé.",
  "O chuveiro elétrico tinha só duas opções: gelado ou escaldante. Encontrar a posição certa do registro era uma ciência que só os moradores dominavam.",
  "O barco a vela deslizava em silêncio pela lagoa, empurrado pelo vento. Quem estava a bordo esqueceu as horas e só lembrou de voltar quando escureceu.",
  "O pacote de biscoitos foi aberto para provar só um, mas acabou na mesma tarde. Ninguém lembra exatamente como, mas todos tinham migalhas no colo.",
  "A loja de bicicletas consertava pneus enquanto o cliente esperava tomando café. O dono contava histórias de viagens que tinha feito pedalando pelo país.",
  "O pé de maracujá subiu pela cerca e invadiu o quintal do vizinho. As frutas que caíam do outro lado eram devolvidas em forma de suco gelado.",
  "A televisão antiga da casa de campo só pegava dois canais, e com chuvisco. Mesmo assim, foi diante dela que a família viu a final do campeonato.",
  "O sino da escola foi trocado por uma música, e os alunos estranharam. Em uma semana, todo mundo cantava a melodia na saída, como um hino.",
  "A banca de frutas tinha uma placa escrita à mão: \"Prove antes de levar.\" Os clientes provavam tanto que, às vezes, saíam satisfeitos sem comprar nada.",
  "O guarda-chuva colorido virou ponto de referência para encontrar a família na praia. Bastava procurar aquelas listras no meio da areia para chegar.",
  "O aniversário do avô reuniu quatro gerações na mesma mesa. Ele passou a festa contando histórias antigas, e cada neto ouvia como se fosse a primeira vez.",
  "O coqueiro da praia estava tão inclinado que parecia prestes a cair na água. Mesmo assim, resistia firme ali havia décadas, como cartão-postal do lugar.",
  "A lanterna de pilha falhou bem na hora de procurar o disjuntor. A solução foi usar a luz do celular, e todos descobriram onde ficava o quadro de luz.",
  "O cheiro de bolo de laranja tomou conta do apartamento inteiro. Os vizinhos do corredor bateram na porta perguntando se tinha sobrado alguma fatia.",
  "O gato aprendeu a abrir o armário da cozinha onde fica a ração. Agora, a porta precisa de um elástico, e ele passa as tardes tentando descobrir o truque.",
  "O caminho da roça era iluminado só pela lua e pelos vaga-lumes. As crianças tentavam pegar os pontinhos de luz com as mãos, sem nunca conseguir.",
  "A primeira viagem de avião da criança foi marcada por um rosto colado na janela. Ela narrou cada nuvem como se estivesse vendo o mundo pela primeira vez.",
  "O restaurante japonês tinha uma esteira com pratos que passavam sem parar. A família inteira ficou hipnotizada, pegando um prato atrás do outro.",
  "O bairro antigo tinha ruas de pedra e casarões coloridos com janelas altas. Andar por ali era como entrar num livro de história, só que com cheiro de café.",
  "O cachorro do porteiro dorme dentro da guarita, ao lado do rádio ligado. Quando toca música sertaneja, ele levanta a orelha e balança o rabo no ritmo.",
  "A sala de aula ficou em silêncio quando a professora anunciou a prova surpresa. Depois, ela riu e explicou que era brincadeira de primeiro de abril.",
  "A melancia era tão grande que precisou de duas pessoas para carregar. Foi aberta no quintal, e o caldo escorreu pelos braços de todo mundo.",
  "O som da máquina de costura acompanhava as tardes na casa da avó. Enquanto ela costurava, os netos brincavam com os carretéis de linha no chão.",
  "A escova de dentes do hotel veio num pacotinho impossível de abrir. Depois de muita luta, o pacote foi vencido com a ajuda de uma tesoura de unha.",
  "O caminhão de frutas parava na esquina toda quinta-feira de manhã. O vendedor anunciava as ofertas num alto-falante que acordava o bairro inteiro.",
  "A árvore de Natal ficou montada até março porque ninguém queria desmontar. No fim, ela virou árvore de Páscoa, com ovinhos coloridos pendurados.",
  "O passeio de bicicleta terminou na sorveteria, como sempre. Ninguém lembra de quem foi a ideia, mas a tradição já tinha virado lei na família.",
  "A goteira do quarto pingava num balde, num ritmo que parecia um relógio. Depois de algumas noites, ficou tão familiar que ajudava a dormir.",
  "O artista da praça fazia esculturas de areia que pareciam castelos de verdade. As ondas levavam tudo no fim da tarde, e no dia seguinte ele começava outra.",
  "O cachorro descobriu a piscina e não queria mais sair da água. Depois do banho, sacudiu-se bem ao lado de quem estava tomando sol, de propósito.",
  "A barraca de pastel da feira tinha uma placa com mais de trinta sabores. Mesmo assim, a maioria dos clientes pedia sempre o mesmo de carne.",
  "O apagão deixou o prédio inteiro no escuro durante o jantar. Os vizinhos se reuniram no hall com lanternas, e alguém trouxe bolo para dividir.",
  "O caderno de anotações do avô tinha listas de pássaros vistos ao longo de décadas. Cada registro tinha data, local e um pequeno desenho a lápis.",
  "A fila do pão francês de domingo saía da padaria e ocupava a calçada. Quem chegava às sete pegava o pão ainda quente, saindo do forno.",
  "O guaxinim do zoológico lavava a comida antes de comer, com toda a calma. As crianças ficaram tão impressionadas que lavaram as mãos sem reclamar.",
  "A cozinheira da pensão fazia um feijão que atraía gente de outros bairros. Ela dizia que o segredo era o tempo, e que feijão bom não gosta de pressa.",
  "O dia de sol depois de uma semana de chuva levou todo mundo para a rua. As praças encheram, os varais lotaram e até os cachorros pareciam sorrir.",
  "O velho ônibus da excursão subia a serra devagar, roncando a cada curva. Os passageiros torciam em silêncio, e no topo todo mundo aplaudiu o motorista.",
  "A coruja da torre da igreja aparecia sempre ao entardecer. Os moradores diziam que ela vigiava a cidade, e ninguém tinha coragem de espantá-la.",
  "O piquenique foi montado com toalha xadrez, cesta de vime e sanduíches caprichados. A chuva apareceu na primeira mordida, e o lanche terminou dentro do carro.",
  "A torneira do jardim tinha uma mangueira tão comprida que alcançava a rua. As crianças inventaram que era um dragão e brincavam de domá-lo.",
  "O mercado do bairro tocava músicas antigas no alto-falante o dia todo. Os clientes mais velhos cantarolavam entre as prateleiras sem perceber.",
  "O pato de borracha da banheira virou o brinquedo favorito do bebê. Ele só aceitava tomar banho se o pato estivesse lá, flutuando de olho nele.",
  "A ventania espalhou as folhas secas pelo quintal inteiro de uma vez. As crianças fizeram um monte enorme e pularam nele até cansar.",
  "A cafeteria da esquina desenhava corações na espuma de cada xícara. Às vezes, para os clientes antigos, o desenho era um gato ou uma flor.",
  "O despertador tocou às cinco da manhã para ver o nascer do sol na praia. Às cinco e dez, todos estavam de volta embaixo do cobertor.",
  "O caminho até a cachoeira tinha uma ponte de pedras escorregadias. Ninguém atravessou sem molhar os pés, e a risada era garantida a cada tropeço.",
  "A coleção de ímãs de geladeira contava todas as viagens da família. Cada um tinha uma história, e as visitas sempre perguntavam sobre os mais estranhos.",
  "O cachorro de rua escolheu a porta da padaria como casa. Ganhou um nome, um pote de água e virou mascote de todos os clientes da manhã.",
  "A torre de blocos ficou tão alta que encostou no teto da sala. A criança olhou orgulhosa, e o gato derrubou tudo com uma única patada.",
  "O vendedor de amendoim torrado passava pelo estádio com uma lata aquecida. O cheiro chegava antes dele, e as mãos se levantavam nas arquibancadas.",
  "A aula de culinária terminou com farinha até no cabelo dos alunos. Os pães saíram tortos, mas foram comidos com muito orgulho por todos.",
  "O rádio do carro só pegava uma estação na estrada de terra. Por três horas, a viagem teve a mesma trilha sonora, e todo mundo aprendeu as letras.",
  "A casa da árvore foi construída com tábuas velhas e muita imaginação. Tinha janela, bandeira e uma regra: adultos só entravam com convite.",
  "O bolo de chocolate da padaria tinha uma cobertura tão brilhante que parecia espelho. Quem comprava uma fatia sempre voltava no dia seguinte para outra.",
  "A feira de livros usados ocupava a praça inteira no primeiro domingo do mês. Era possível encontrar raridades por poucas moedas, se a busca fosse paciente.",
  "O chão de madeira da casa antiga rangia em lugares específicos. Os filhos aprenderam a pisar só nas tábuas silenciosas para chegar tarde sem ser notados.",
  "O ônibus de excursão parou num restaurante de estrada famoso pelo pão de queijo. A parada de vinte minutos durou quase uma hora, e ninguém reclamou.",
  "O papagaio do sítio aprendeu a chamar o cachorro pelo nome. O pobre animal corria até a varanda várias vezes por dia, sem entender de onde vinha a voz.",
  "A colher de pau da avó era usada para mexer doces e para manter a ordem na cozinha. Bastava ela levantá-la para os netos saírem correndo, rindo.",
  "O telefone tocou no meio do filme bem na cena mais importante. Era engano, e a pessoa do outro lado ainda pediu desculpas por ter atrapalhado.",
  "O quintal da escola tinha uma mangueira centenária que dava sombra para todos. Na hora do recreio, as crianças disputavam um lugar debaixo dela.",
  "A sacola de feira voltou cheia de frutas, verduras e um vaso de flores. As flores não estavam na lista, mas ninguém resiste a uma boa barraca de plantas.",
  "O avião de papel voou da janela do terceiro andar e pousou no chapéu de um senhor. Ele olhou para cima, sorriu e lançou o avião de volta com perfeição.",
  "O gato fica sentado na janela observando os passarinhos por horas. Ele faz um barulhinho engraçado com a boca, como se estivesse conversando com eles.",
  "A loja de doces tinha potes de vidro com balas de todas as cores. As crianças entravam com uma moeda e passavam meia hora escolhendo o que levar.",
  "O cheiro de mato depois da chuva entrava pela janela do ônibus. Os passageiros que dormiam acordaram, abriram os olhos e respiraram fundo.",
  "O livro de receitas da escola reuniu os pratos favoritos de cada família. A turma vendeu os exemplares na festa e arrecadou o suficiente para a excursão.",
  "A primeira geada do ano deixou a grama branca e o carro coberto de gelo. As crianças desenharam no vidro antes que o sol derretesse tudo.",
  "O vizinho que toca violino ensaiava sempre com a janela aberta. Nos dias de concerto, os moradores do prédio ouviam a apresentação de graça da varanda.",
  "A lancha deu uma volta pela baía no fim da tarde, quando o mar estava calmo. Os golfinhos apareceram por alguns segundos, e ninguém conseguiu fotografar.",
  "O pé de alecrim da janela perfumava a cozinha inteira. Bastava encostar a mão nas folhas para o cheiro ficar nos dedos por horas.",
  "O campeonato de bolinha de gude no recreio tinha regras complicadas e muitos juízes. No fim, todo mundo ganhava pelo menos uma bolinha nova.",
  "O sorriso da criança ao ver o mar pela primeira vez ficou na memória da família. Ela correu até a água, recuou com a onda e voltou correndo, rindo.",
  "A chuva fina da manhã deixou a cidade cinzenta e silenciosa. Na padaria, o cheiro de café e pão quente parecia ainda mais acolhedor que o normal.",
  "O carrinho de mão do jardineiro virou carro de corrida para as crianças. Elas passaram a tarde se revezando, uma empurrando e outra gritando de alegria.",
  "O almoço de domingo terminou, mas ninguém levantou da mesa. A conversa foi ficando boa, o café foi servido e, quando perceberam, já era hora do lanche.",
];
