export const TEXTOS = [
  "Na feira de sábado, o vendedor de frutas sabia de cor o preço de tudo, quanto tinha vendido na semana anterior e quais clientes voltariam antes do meio-dia.",
  "O cheiro de bolo saindo do forno tomou conta da casa inteira. Em poucos minutos, todo mundo apareceu na cozinha perguntando, sem nenhuma pressa, se já dava para cortar.",
  "A trilha começava larga e bem marcada, mas depois da ponte de madeira virava um caminho estreito entre as árvores. Lá no alto, a vista compensava cada passo.",
  "Minha avó guardava os botões numa lata de biscoitos. Quando chovia, a gente despejava tudo sobre a mesa e passava a tarde separando por cor e tamanho.",
  "O último ônibus da noite passou vazio pela avenida. O motorista cantava baixinho uma música antiga, e as luzes da cidade iam ficando para trás, uma a uma.",
  "Plantar uma árvore é um gesto de confiança no futuro: quem planta raramente descansa na sombra, mas alguém, algum dia, vai agradecer em silêncio.",
  "Aprender um instrumento exige paciência. As primeiras semanas soam estranhas, os dedos doem e as notas escapam, até que um dia a música simplesmente acontece.",
  "O cachorro do vizinho late toda vez que o carteiro chega, mas abana o rabo com tanta vontade que ninguém consegue levar a bronca a sério.",
  "O farol da ilha funciona há mais de cem anos, girando a mesma luz todas as noites. Os pescadores mais antigos dizem que, sem ele, o mar pareceria muito maior. Hoje ele é automático, mas o antigo faroleiro ainda visita o lugar aos domingos.",
  "A receita de pão de queijo da família passou por quatro gerações sem nunca ser escrita. Cada pessoa aprendeu olhando, errando e provando. Por isso, cada versão tem um detalhe diferente, e todos juram que a sua é a original.",
  "O inverno na serra tem um ritual próprio: lareira acesa, chocolate quente e cobertor no sofá. Lá fora, o vento assobia entre os pinheiros. Dentro de casa, ninguém tem pressa de fazer nada além de conversar.",
  "O menino passou a tarde inteira tentando ensinar o cachorro a sentar. O cachorro aprendeu a deitar, a rolar e a pedir comida, mas sentar, que era o objetivo, ficou para outro dia.",
  "A biblioteca da cidade fica num prédio antigo, com janelas altas e escadas de madeira. Os livros mais raros ficam numa sala trancada, e só a bibliotecária tem a chave. Ela conhece cada volume como se fosse um velho amigo.",
  "Andar de bicicleta pela orla no fim da tarde é um dos programas mais simples e mais bonitos da cidade. O vento vem do mar, o céu muda de cor a cada minuto e o barulho das ondas acompanha as pedaladas.",
  "O vendedor de livros usados da praça monta a barraca todos os dias às oito horas. Ele lê enquanto espera os clientes e recomenda títulos com tanto entusiasmo que é difícil sair de lá sem levar pelo menos um.",
  "A horta comunitária do bairro começou com três canteiros e hoje ocupa um terreno inteiro. Cada morador cuida de um pedaço, e a colheita é dividida entre todos. Nas manhãs de domingo, o lugar vira ponto de encontro.",
  "O relógio de parede da casa da avó faz tique-taque tão alto que dá para ouvir da cozinha. À noite, no silêncio, ele parece marcar o ritmo da casa inteira, como um coração antigo.",
  "Cozinhar para muitas pessoas é uma arte que exige planejamento. É preciso calcular as porções, organizar o tempo de cada panela e, principalmente, aceitar que alguém sempre vai repetir o prato.",
  "O parque de diversões chegou à cidade e montou a roda-gigante no terreno ao lado da igreja. Durante um mês, as noites ficaram coloridas, e o cheiro de algodão-doce se espalhou por todas as ruas próximas.",
  "A coleção de selos do avô ocupava três álbuns grossos de capa de couro. Cada selo vinha de um país diferente, e ele sabia contar a história de todos, mesmo dos que nunca tinha visitado.",
  "O treino de corrida começou com dois quilômetros e muito cansaço. Três meses depois, os mesmos dois quilômetros eram só o aquecimento. A melhor parte foi descobrir que a constância vale mais do que a velocidade.",
  "No interior, as notícias chegam mais rápido pela janela do vizinho do que pela televisão. Um nascimento, uma visita ou uma reforma viram assunto da cidade inteira em poucas horas.",
  "A sorveteria artesanal da esquina muda os sabores conforme as frutas da estação. No verão, tem manga e maracujá; no inverno, tangerina e goiaba. Os clientes fiéis acompanham o calendário como quem espera uma festa.",
  "O avião decolou com atraso, mas o piloto prometeu recuperar o tempo no ar. Chegou dez minutos antes do horário previsto, e os passageiros aplaudiram como se tivesse sido um milagre.",
  "A oficina de marcenaria do bairro ensina adultos a fazer pequenos móveis. Os primeiros trabalhos saem tortos, mas cada banquinho bambo é levado para casa com um orgulho enorme.",
  "Quando a energia acabou, a família descobriu que não sabia mais brincar sem telas. Depois de alguns minutos de silêncio constrangido, alguém pegou um baralho, e a noite terminou cheia de risadas.",
  "O cais do porto acorda antes do sol. Os barcos chegam com a pesca da noite, os compradores negociam em voz alta e as gaivotas sobrevoam tudo, esperando a sua parte.",
  "O prédio tem um grupo de mensagens para assuntos importantes, como vazamentos e entregas. Na prática, ele é usado para fotos de gatos, receitas de bolo e discussões sobre a vaga da garagem.",
  "Fazer uma mala para uma viagem longa é um exercício de escolhas. Cada peça precisa justificar seu espaço, e no fim sempre sobra a dúvida sobre aquele casaco que talvez não seja necessário.",
  "A cidade ganhou uma ciclovia nova, e as primeiras semanas foram de adaptação. Pedestres, ciclistas e motoristas aprenderam aos poucos a dividir o espaço, e hoje ninguém imagina a avenida sem ela.",
  "O circo armou a lona no campo do bairro e mudou a rotina das crianças. Durante dias, elas tentaram equilibrar vassouras no nariz e fazer malabarismo com laranjas, com resultados muito variados.",
  "O feirante de verduras arruma as alfaces como se fossem flores, em fileiras perfeitas. Ele diz que a primeira compra é feita com os olhos, e que verdura bonita vende sozinha.",
  "A tarde de chuva foi dedicada a organizar as fotos do celular. Entre milhares de imagens repetidas e capturas de tela esquecidas, apareceram lembranças que ninguém lembrava de ter registrado.",
  "O museu da cidade guarda objetos do dia a dia de cem anos atrás: ferros de passar a carvão, máquinas de escrever e brinquedos de lata. As crianças ficam fascinadas com coisas que os avós usavam.",
  "A estrada que leva à praia tem uma curva famosa de onde se avista o mar pela primeira vez. Toda família tem o seu ritual nesse ponto: uns gritam, outros aplaudem e alguns ficam em silêncio.",
  "Aprender a nadar depois de adulto exige coragem. O começo é cheio de água engolida e braçadas desajeitadas, mas a primeira travessia da piscina sem parar vale como uma medalha de ouro.",
  "O vizinho do andar de baixo cultiva orquídeas na varanda há trinta anos. Quando alguma floresce, ele bate na porta dos vizinhos para mostrar, com o mesmo entusiasmo da primeira vez.",
  "A festa da colheita na cidadezinha dura três dias e reúne gente de toda a região. Tem música, comidas típicas, concurso de bolo e uma corrida de carrinhos de rolimã na ladeira principal.",
  "O primeiro emprego ensinou lições que nenhuma escola tinha ensinado: chegar no horário, pedir ajuda quando necessário e entender que todo trabalho, por mais simples, tem a sua importância.",
  "O gato da casa tem um horário rígido para cada atividade. Acorda às seis, pede comida às seis e cinco e dorme no sofá às sete. Qualquer atraso na rotina é recebido com miados de protesto.",
  "O lago do parque congela em pouquíssimos lugares do país, mas a cidade da serra é um deles. Nas manhãs mais frias do ano, moradores e turistas saem cedo para fotografar a camada fina de gelo.",
  "O cozinheiro de rua prepara cachorros-quentes com uma lista enorme de complementos. Batata palha, milho, ervilha, purê e vinagrete: tudo cabe no pão, desde que o cliente tenha coragem.",
  "A primeira vez que a família acampou foi uma sequência de pequenos desastres. A barraca molhou, o fogareiro não acendeu e um sapo invadiu a cozinha improvisada. Mesmo assim, todos quiseram repetir.",
  "O ônibus de linha que liga os bairros mais distantes faz um percurso de quase duas horas. Os passageiros frequentes já se conhecem, guardam lugar uns para os outros e comemoram aniversários a bordo.",
  "O escritório ganhou uma máquina de café nova, e a produtividade mudou. Agora, as melhores ideias surgem na fila do café, entre uma conversa e outra, longe das mesas de trabalho.",
  "O mestre de obras explicava tudo com desenhos feitos a lápis no próprio cimento. Os pedreiros entendiam na hora, e as paredes subiam retas, sem uma única régua de diferença.",
  "A cidade costeira recebe milhares de turistas no verão e fica quase vazia no inverno. Os moradores dizem que as duas estações são boas: uma pelo movimento, a outra pelo sossego.",
  "Ler em voz alta para uma criança é um dos melhores presentes que se pode dar. As vozes dos personagens, as pausas de suspense e as perguntas no meio da história ficam na memória por muitos anos.",
  "O passeio de barco pelo rio passava por vilarejos onde as casas ficavam sobre palafitas. As crianças acenavam das janelas, e os turistas respondiam como se fossem velhos conhecidos.",
  "O jardim japonês do parque tem um lago com carpas coloridas e uma ponte vermelha. É o lugar mais silencioso da cidade, e muita gente vai até lá só para sentar e observar a água.",
  "O cinema de rua da cidade fechou nos anos noventa e ficou abandonado por muito tempo. Recentemente, um grupo de moradores reformou o prédio, e as sessões de sábado voltaram a lotar a sala.",
  "A arte de fazer pipa passa de geração em geração no bairro. Os mais velhos ensinam a cortar o papel de seda, a escolher as varetas e a fazer a rabiola, sempre com muita paciência.",
  "O piloto de balão explicou que não dá para escolher o destino, só a altura. O vento decide para onde ir, e o trabalho é encontrar a corrente certa, como quem procura uma estrada invisível no céu.",
  "O consultório do veterinário tem uma sala de espera sempre animada. Cachorros, gatos, coelhos e até um papagaio dividem o espaço, cada um com o seu jeito de mostrar que não quer estar ali.",
  "O inverno trouxe a temporada dos pinhões, e a cozinha virou uma pequena fábrica. Cozidos, assados ou na paçoca, eles aparecem em todas as refeições até o último saco acabar.",
  "A professora de artes pediu que cada aluno desenhasse a própria casa. Saíram castelos, foguetes, casas na árvore e até um submarino. Nenhum desenho parecia com a casa de verdade, e todos estavam certos.",
  "O mercado de peixes abre às quatro da manhã e fecha antes das dez. Quem quer o pescado mais fresco precisa enfrentar o sono e o frio, mas os cozinheiros dizem que vale cada minuto.",
  "O time de vôlei de praia treinava todos os dias às seis da manhã, antes do sol ficar forte. Os banhistas que chegavam cedo assistiam aos jogos como se fosse uma partida de campeonato.",
  "A loja de conserto de relógios fica numa portinha estreita do centro antigo. O relojoeiro trabalha com uma lupa no olho e uma calma impressionante, cercado por centenas de tique-taques diferentes.",
  "A mudança para uma cidade nova traz um período estranho de adaptação. As ruas não têm memórias, os rostos não são conhecidos e até o caminho da padaria precisa ser aprendido do zero.",
  "O bolo de casamento tinha cinco andares e flores feitas de açúcar. Ficou tão bonito que ninguém queria cortar, e a festa só ganhou a sobremesa depois de muitas fotos.",
  "O sítio da família tem um riacho de água gelada onde as crianças passam as tardes de verão. Elas constroem pequenas represas com pedras e soltam barquinhos feitos de folhas.",
  "Aprender um idioma novo depois de adulto é uma mistura de vergonha e descoberta. Cada frase dita corretamente parece uma vitória, e cada erro vira uma boa história para contar depois.",
  "O feriado de carnaval esvaziou o escritório, e quem ficou trabalhou em silêncio total. O telefone não tocou, os e-mails pararam e o café durou o dia inteiro na garrafa térmica.",
  "A doceira do bairro faz bolos decorados para todas as festas da região. Ela trabalha na cozinha de casa, com uma geladeira só para os bolos e uma fila de encomendas que vai até o fim do mês.",
  "O guarda-florestal conhece cada trilha do parque nacional como a palma da mão. Ele identifica os pássaros pelo canto e as árvores pela casca, e conta histórias que parecem lendas.",
  "A primeira geladeira da casa, comprada pelos avós, funcionou por mais de quarenta anos. Era barulhenta, pesada e tinha um puxador de metal, mas nunca deixou ninguém sem água gelada.",
  "O passeio pelo centro histórico terminou numa confeitaria fundada há mais de um século. Os doces seguem receitas antigas, e as mesas de mármore guardam o mesmo charme de sempre.",
  "O treinador do time infantil dizia que o resultado importava menos do que a amizade. Mesmo assim, quando o time ganhou o primeiro jogo da temporada, ele foi o que mais comemorou.",
  "A estação de esqui mais próxima fica a milhares de quilômetros, então a família inventou a sua própria neve. Uma máquina de raspar gelo e muita imaginação transformaram o quintal num inverno particular.",
  "O vendedor de balões da praça carrega dezenas deles presos por fios coloridos. Nos dias de vento, parece que a qualquer momento ele vai sair voando junto com a mercadoria.",
  "O sebo da rua de trás tem livros empilhados do chão até o teto, sem nenhuma organização aparente. O dono, porém, sabe exatamente onde está cada título e encontra qualquer pedido em segundos.",
  "A viagem de carro pelo litoral foi feita sem roteiro definido. A família parava onde achava bonito, comia onde parecia gostoso e dormia onde havia vaga. Foi a viagem mais lembrada de todas.",
  "O professor de química fazia experiências que mudavam de cor e soltavam fumaça. Os alunos prestavam tanta atenção que até os mais distraídos sabiam explicar as reações no fim da aula.",
  "O caminhão de bombeiros visitou a escola, e as crianças puderam subir na escada e usar o capacete. A maior parte delas decidiu, naquele mesmo dia, qual seria a profissão no futuro.",
  "A tradição da família é tirar uma foto no mesmo lugar todos os anos, no mesmo dia. Colocadas lado a lado, as fotos mostram cabelos mudando, crianças crescendo e a árvore ao fundo ficando enorme.",
  "O jardim de chuva da praça foi projetado para receber a água dos temporais. Em vez de alagar a rua, a água infiltra no solo, e as plantas crescem mais verdes a cada estação.",
  "A banda de garagem ensaiava todos os sábados, para desespero de alguns vizinhos. Anos depois, quando tocou num festival da cidade, os mesmos vizinhos estavam na primeira fila.",
  "O mestre-cuca do restaurante de beira de estrada serve a mesma comida há trinta anos. Arroz, feijão, bife e salada, sem invenção nenhuma. Os viajantes param ali justamente por isso.",
  "O primeiro celular da família era do tamanho de um tijolo e só fazia ligações. Hoje ele fica numa prateleira, como peça de museu, e as crianças não acreditam que aquilo já foi novidade.",
  "A rua de lazer de domingo fecha a avenida para os carros e abre espaço para pessoas. Patins, bicicletas, cachorros e carrinhos de bebê dividem o asfalto até o fim da tarde.",
  "O cozinheiro ensinou que a cebola deve dourar devagar, sem pressa. Segundo ele, metade do sabor de um prato está nos minutos que ninguém quer esperar diante do fogão.",
  "A estrada de ferro desativada virou uma trilha para caminhadas e bicicletas. Os antigos túneis e pontes agora recebem pessoas a pé, e as estações abandonadas viraram pontos de descanso.",
  "O festival de inverno da cidade reúne apresentações de música, teatro e dança. Durante duas semanas, as praças ficam cheias de gente agasalhada, com copos de quentão nas mãos.",
  "A primeira aula de direção foi marcada por solavancos, buzinas e muita paciência do instrutor. No fim do mês, o carro já andava suave, e até a baliza saía na primeira tentativa.",
  "O florista do mercado municipal monta arranjos com flores do campo, galhos secos e folhagens. Cada buquê é diferente, e ele diz que não sabe repetir nenhum, mesmo quando tenta.",
  "A família guarda numa caixa todos os bilhetes trocados entre os seus membros ao longo dos anos. Há recados de geladeira, cartões de aniversário e desenhos de criança com letras tortas.",
  "O inverno no sul traz dias curtos e noites longas, perfeitas para receber amigos em casa. Uma panela de sopa, pão quentinho e boa conversa transformam qualquer noite fria num encontro.",
  "O artesão de cerâmica trabalha no torno com as mãos sempre sujas de barro. Ele diz que o barro tem vontade própria e que o segredo é escutar o que a peça quer ser.",
  "O balneário de água doce é o destino preferido das famílias da região nas férias. A água é calma, a areia é fina e as barracas vendem peixe frito e milho cozido o dia inteiro.",
  "O vizinho aposentado decidiu aprender a fazer pão e transformou a cozinha num laboratório. Agora ele distribui as fornadas pelo prédio e recebe sugestões de sabores como se fosse uma padaria.",
  "O planetário da cidade apaga as luzes e projeta o céu estrelado na cúpula. Por alguns minutos, os visitantes esquecem onde estão e viajam por constelações e planetas distantes.",
  "O corredor da escola guarda troféus de campeonatos de décadas atrás. Os alunos passam por eles todos os dias, sem imaginar que alguns dos campeões são hoje seus próprios avós.",
  "A estrada de terra até a fazenda vira lama em dias de chuva. Por isso, os moradores mantêm um trator na entrada, pronto para puxar os carros dos visitantes desavisados.",
  "A turma da faculdade se reúne uma vez por ano para um jantar, sempre no mesmo restaurante. As histórias são as mesmas, mas a cada encontro ganham detalhes novos e muito mais exagerados.",
  "O gato da livraria dorme nas pilhas de lançamentos e escolhe o livro mais caro como travesseiro. Os clientes tiram fotos, e o dono diz que ele é o melhor vendedor da loja.",
  "O porto de pesca da vila tem barcos pintados de cores vivas, cada um com um nome escrito à mão. Os pescadores dizem que o nome certo traz sorte e que barco sem nome não volta cheio.",
  "O cheiro do café torrado na hora se espalha por todo o quarteirão da torrefação. Os moradores dizem que não precisam de despertador, porque o aroma chega antes do sol.",
  "O caderno de viagens da tia tem colagens de mapas, ingressos e flores secas. Cada página é uma lembrança diferente, e folhear o caderno é quase como fazer a viagem de novo.",
  "A ponte pênsil sobre o rio balança com o vento e assusta quem atravessa pela primeira vez. Os moradores, acostumados, passam carregando compras e conversando, sem nem segurar no corrimão.",
  "O mutirão de limpeza da praia reuniu voluntários de todas as idades numa manhã de domingo. Em poucas horas, sacos e mais sacos foram recolhidos, e a areia ficou limpa como há muito tempo não se via.",
  "O músico de rua toca saxofone todas as tardes na saída do metrô. Muita gente passa apressada, mas sempre há quem pare, feche os olhos e deixe a música mudar o rumo do dia.",
  "A casa de bonecas da avó tinha móveis em miniatura feitos à mão, com gavetas que abriam de verdade. As netas brincavam com cuidado, sabendo que aquele era um tesouro da família.",
  "A prova de matemática parecia impossível na véspera. Depois de uma noite de estudo e muitas folhas de rascunho, as questões fizeram sentido, e a nota foi a melhor do ano.",
  "O sítio arqueológico perto da cidade revelou ferramentas usadas por povos antigos. As escolas da região organizam visitas, e as crianças voltam querendo ser exploradoras.",
  "O restaurante de comida caseira tem um cardápio escrito a giz num quadro-negro. Todos os dias muda alguma coisa, mas o pudim de leite está lá sempre, no mesmo canto.",
  "A estrada para o observatório sobe a montanha em curvas fechadas. No topo, longe das luzes da cidade, o céu noturno mostra estrelas que a maioria das pessoas nunca viu.",
  "O professor de violão ensinava com paciência e um bom humor que não acabava. Quando um aluno errava o acorde, ele dizia que aquela nota estranha podia ser o começo de uma música nova.",
  "O carnaval de rua da cidade pequena tem um único bloco, mas todo mundo participa. As fantasias são feitas em casa, a bateria é formada por vizinhos e a alegria não tem hora para acabar.",
  "A coleção de discos de vinil do tio ocupa uma parede inteira da sala. Ele guarda cada disco no plástico e só deixa os sobrinhos tocarem depois de uma aula sobre como segurar a agulha.",
  "O gramado do estádio é cuidado como um jardim premiado. Os jardineiros cortam a grama em listras perfeitas e regam em horários exatos, para que a bola role sempre do mesmo jeito.",
  "O empório do bairro vende queijos, doces e cachaças de pequenos produtores. O dono oferece prova de tudo, conta a origem de cada produto e conhece os fabricantes pelo nome.",
  "O apagão da cidade inteira transformou a noite numa experiência rara. Sem luz nas ruas, as estrelas apareceram no céu urbano, e muita gente subiu nas lajes para observar.",
  "O treino de natação da equipe começa antes do sol nascer, com a água ainda fria. Os nadadores reclamam no primeiro mergulho, mas saem da piscina com a sensação de ter vencido o dia.",
  "A pequena livraria de bairro organiza encontros de leitura todas as quintas-feiras. Os participantes debatem os livros, trocam indicações e, muitas vezes, terminam a noite conversando sobre a vida.",
  "O primeiro dia de neve na cidade da serra foi notícia em todos os jornais da região. Os moradores saíram de casa de pijama, fizeram bonecos de neve e guardaram flocos no congelador.",
  "A oficina de bicicletas comunitária ensina as pessoas a consertar a própria bicicleta. As ferramentas ficam disponíveis, e os voluntários ajudam a trocar câmaras, ajustar freios e regular marchas.",
  "O feirante de queijos corta uma lasca para cada cliente provar. Ele explica a diferença entre o curado e o fresco com tanto entusiasmo que até quem não gosta de queijo acaba levando um pedaço.",
  "O sino da capela tocava ao meio-dia para avisar a hora do almoço na lavoura. Mesmo com relógios e celulares, os trabalhadores ainda param quando ouvem aquele som familiar.",
  "A pousada da serra recebe os hóspedes com uma lareira acesa e um bolo recém-saído do forno. Os quartos não têm televisão, e ninguém sente falta, porque a vista da janela basta.",
  "O parque tem uma árvore centenária cercada por um banco circular de madeira. É o ponto de encontro preferido de casais, amigos e leitores solitários, que disputam a sombra nos dias quentes.",
  "A campanha de doação de livros do bairro superou todas as expectativas. Em um mês, as caixas encheram a sala da associação, e a escola ganhou uma biblioteca nova.",
  "A tradição do almoço de domingo na casa dos avós resiste ao tempo. A mesa aumenta a cada ano, com novos namorados, bebês e amigos, mas o cardápio continua exatamente o mesmo.",
  "O pescador mais velho da vila ensina os jovens a ler o tempo pelas nuvens e pelo vento. Ele raramente erra, e as previsões dele são mais respeitadas do que as da televisão.",
  "O viveiro de mudas da prefeitura distribui árvores de graça para quem quiser plantar. Em poucos anos, as calçadas do bairro ganharam sombra, flores e muitos passarinhos.",
  "O primeiro espetáculo da escola de dança teve figurinos costurados pelas próprias famílias. No palco, as crianças esqueceram alguns passos, mas a plateia aplaudiu cada movimento.",
  "A antiga fábrica de tecidos foi transformada num centro cultural. As máquinas ficaram como decoração, e os galpões agora recebem exposições, feiras e apresentações de teatro.",
  "O motorista de aplicativo deixava balas e garrafinhas de água para os passageiros. Dizia que gentileza não custa caro e que as melhores avaliações vinham das pequenas atenções.",
  "O campeonato de xadrez da escola reuniu alunos de todas as séries. O campeão foi um menino do quarto ano, que derrotou adversários mais velhos com uma calma impressionante.",
  "A casa de veraneio da família tem uma rede em cada canto da varanda. Nas tardes quentes, o único barulho é o balanço das redes e, de vez em quando, um ronco mais alto.",
  "O curso de fotografia ensinou que a luz é mais importante que a câmera. Os alunos passaram a observar o sol da manhã, as sombras da tarde e o brilho das janelas à noite.",
  "O tradicional bolo de rolo da tia tem tantas camadas que é impossível contar. Ela diz que o segredo é a paciência para enrolar a massa fina sem deixar rasgar.",
  "O vale coberto de neblina parece um mar de nuvens visto do alto do mirante. Quem acorda cedo para ver a cena diz que é como estar acima do mundo por alguns minutos.",
  "O clube de ciclismo da cidade organiza passeios noturnos pelas avenidas iluminadas. Os ciclistas enfeitam as bicicletas com luzes coloridas, e o grupo parece um desfile em movimento.",
  "A merenda da escola municipal ganhou fama depois que uma nutricionista mudou o cardápio. Agora as crianças comem verduras da horta da própria escola e pedem para repetir a salada.",
  "A estação rodoviária antiga ganhou bancos novos, plantas e um painel com os horários. Mesmo assim, o que os viajantes mais elogiam é o café da lanchonete, que continua igual há décadas.",
  "O festival de pipas do litoral reúne pessoas de várias cidades na praia ventosa. Há pipas em forma de peixe, dragão e até de polvo gigante, e o céu vira uma galeria flutuante.",
  "A senhora que mora na esquina dá bom-dia a todos que passam pela calçada. Os vizinhos dizem que a rua fica mais leve só por causa daquele cumprimento diário.",
  "O torneio de futebol de botão do bairro é levado mais a sério do que muitos campeonatos de verdade. Os jogadores têm times personalizados, regras próprias e até uma taça de lata.",
  "O passeio de trem antigo atravessa plantações de café e pequenas estações coloridas. O maquinista apita a cada curva, e as crianças acenam para os moradores que aparecem nas janelas.",
  "O laboratório de informática da escola recebeu computadores doados por uma empresa. Os alunos aprenderam a programar pequenos jogos, e alguns já ajudam os professores nas aulas.",
  "O artista que pinta murais pela cidade transforma muros cinzentos em paisagens coloridas. Os moradores escolhem os temas, e cada obra conta um pouco da história do bairro.",
  "O inverno trouxe a temporada de caldos na lanchonete da esquina. Mandioca, feijão, ervilha e frango: a cada dia um sabor diferente, sempre com pão torrado e cheiro-verde.",
  "O cachorro idoso da família passa os dias deitado no tapete da sala, perto da janela. Mesmo devagar, ele ainda vai até a porta receber cada pessoa que chega em casa.",
  "A trilha das cachoeiras tem sete quedas d'água ao longo de um percurso de cinco quilômetros. Cada uma tem uma cor e um formato diferente, e a última é a mais bonita de todas.",
  "O sorveteiro da praia anda com um carrinho pesado pela areia quente o dia inteiro. Ele conhece os banhistas frequentes e já chega com o sabor preferido de cada um separado.",
  "A reunião de condomínio começou às oito para discutir a pintura da fachada. Às onze, o assunto ainda era a cor, e ninguém tinha chegado a um acordo sobre o tom de bege.",
  "O mercado de flores abre de madrugada para atender floristas de toda a cidade. Quem passa por lá ao amanhecer encontra um corredor colorido e perfumado no meio do concreto.",
  "O ateliê de costura do bairro ensina pessoas a reaproveitar roupas antigas. Camisas viram bolsas, calças viram saias e retalhos se transformam em colchas cheias de memória.",
  "A noite de observação de estrelas no sítio terminou com todos deitados na grama. Ninguém sabia o nome das constelações, então cada um inventou as suas, com histórias e personagens.",
];
